// Generated by CoffeeScript 1.8.0

/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var Duplex, EventEmitter, Hub, HubRequest, Promise, TLS_OPTIONS, concat, defaultBodyParser, defaultHeaders, extend, formatUri, http, https, identity, isEmpty, mime, next, noop, pick, toNull, url, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

http = require('http');

https = require('https');

url = require('url');

EventEmitter = require('events').EventEmitter;

Promise = require('bluebird');

Duplex = require('readable-stream').Duplex;

concat = require('concat-stream');

mime = require('mime-types');

_ref = require('lodash'), extend = _ref.extend, pick = _ref.pick, isEmpty = _ref.isEmpty;

noop = function() {};

toNull = function() {
  return null;
};

identity = function(x) {
  return x;
};

next = function(ee, event) {
  return new Promise(function(resolve, reject) {
    if (event !== 'error') {
      ee.once('error', reject);
    }
    return ee.once(event, resolve);
  });
};

defaultBodyParser = function(body, response) {
  var contentType, err;
  contentType = response.headers['content-type'];
  switch (mime.extension(contentType)) {
    case 'json':
      if (body.length === 0) {
        return void 0;
      } else {
        try {
          return JSON.parse(body.toString('utf8'));
        } catch (_error) {
          err = _error;
          throw err;
        }
      }
      break;
    default:
      return body;
  }
};

HubRequest = (function(_super) {
  __extends(HubRequest, _super);

  function HubRequest(options) {
    var _ref1;
    Duplex.call(this);
    this.bodyParser = (_ref1 = options.bodyParser) != null ? _ref1 : defaultBodyParser;
    this._errorOrNull = next(this, 'end').then(toNull, identity);
  }

  HubRequest.prototype.init = function(_req) {
    this._req = _req;
    this._req.once('error', this.emit.bind(this, 'error'));
    this.response = new Promise((function(_this) {
      return function(resolve, reject) {
        _this._req.once('error', reject);
        return _this._req.once('response', function(response) {
          response.on('data', function(chunk) {
            return _this.push(chunk);
          });
          response.once('end', function() {
            return _this.push(null);
          });
          response.once('error', function(error) {
            return _this.emit('error', error);
          });
          resolve(response);
          return _this.emit('response', response);
        });
      };
    })(this));
    this._stats = {};
    this._write = this._req.write.bind(this._req);
    return this.once('finish', this._finalize.bind(this));
  };

  HubRequest.prototype._read = function(size) {};

  HubRequest.prototype._finalize = function() {
    return this._req.end();
  };

  HubRequest.prototype.getResponse = function(callback) {
    return this.response.nodeify(callback);
  };

  HubRequest.prototype.getRawBody = function(callback) {
    if (this._rawBody == null) {
      this._rawBody = this.response.then((function(_this) {
        return function() {
          return new Promise(function(resolve, reject) {
            _this.once('error', reject);
            return _this.pipe(concat(resolve));
          });
        };
      })(this));
    }
    return this._rawBody.nodeify(callback);
  };

  HubRequest.prototype.getBody = function(callback) {
    return Promise.all([this.getRawBody(), this.response]).spread(this.bodyParser).nodeify(callback);
  };

  HubRequest.prototype.fail = function(error) {
    setImmediate(this.emit.bind(this, 'error', error));
    return this;
  };

  HubRequest.prototype.then = function(success, error, progress) {
    return this.getBody().then(success, error, progress);
  };

  HubRequest.prototype.addDataDump = function(callback) {
    return Promise.all([this._errorOrNull, this.getBody()["catch"](noop), this.getResponse()["catch"](noop), this._stats]).nodeify(function(err, results) {
      if (err != null) {
        return callback(err);
      }
      return callback.apply(null, results);
    });
  };

  return HubRequest;

})(Duplex);

formatUri = function(options) {
  return options.uri;
};

defaultHeaders = function() {
  return {
    accept: 'application/json,*/*;q=0.8'
  };
};

TLS_OPTIONS = ['pfx', 'key', 'passphrase', 'cert', 'ca', 'ciphers', 'rejectUnauthorized', 'secureProtocol'];

Hub = (function(_super) {
  __extends(Hub, _super);

  function Hub() {
    if (!(this instanceof Hub)) {
      return new Hub();
    }
    EventEmitter.call(this);
  }

  Hub.prototype.fetch = function(options, callback) {
    var fullUri, hasBody, httpLib, httpOptions, isHttps, nativeReq, req, tlsOptions, _ref1;
    req = new HubRequest({
      bodyParser: options.bodyParser
    });
    fullUri = formatUri(options);
    if (!fullUri) {
      return req.fail(new Error('A uri is required'));
    }
    httpOptions = extend(url.parse(fullUri), {
      agent: options.agent,
      auth: options.auth,
      headers: extend(defaultHeaders(), (_ref1 = options.headers) != null ? _ref1 : {}),
      localAddress: options.localAddress,
      method: options.method != null ? options.method.toUpperCase() : 'GET'
    });
    tlsOptions = pick(options, TLS_OPTIONS);
    isHttps = httpOptions.protocol === 'https:';
    httpLib = isHttps ? https : http;
    if (isHttps && !isEmpty(tlsOptions)) {
      if (httpOptions.agent === false) {
        extend(httpOptions, tlsOptions);
      } else if (httpOptions.agent == null) {
        return req.fail(new Error('TLS options are not supported when using the global agent'));
      }
    }
    nativeReq = httpLib.request(httpOptions);
    req.init(nativeReq);
    if (options.encoding) {
      req.setEncoding(options.encoding);
    }
    hasBody = httpOptions.method !== 'GET';
    if (!hasBody) {
      req.end();
    }
    if (callback) {
      req.addDataDump(callback);
    }
    return req;
  };

  return Hub;

})(EventEmitter);

module.exports = Hub;
